### ISSUE TITLE
Dereferencing Sanity `image.asset` field typing problem

### ISSUE THREAD

**Issue by matzexcom** [FormidableLabs/groqd#332]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Bug report

Hi, thanks for your work, I am in the middle of migrating from 0.x to 1.x

I have some problems with the `deref` of the Sanity Image field.
A normal Sanity Image field has the following structure

```
image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }

```

My understanding now is that I can do

```
.project((sub) => ({
  imageUrl: sub.field('image.asset').deref().field('url'),
  ...
```

but then typescript complains `Argument of type 'url' is not assignable to parameter of type never` because the `deref` seems to not knowing the result type of `.field('image.asset').deref()`

I tried to use some kind of fragment like 

```
const sanityImage = q.fragmentForType<'sanity.imageAsset'>().project({
  url: q.string().optional().nullable(),
})

.project((sub) => ({
  imageFragment: sub.field('image.asset').deref().project(sanityImage),

```
but than I got the error message from groqd `['⛔️ Error: this projection has an invalid property ⛔️'] | ['⛔️ A parser can only be used for known properties; \'url\' is not known ⛔️']`. The same problem the `defref` does not know the type from `'image.asset' `

I found a work around for that, so that typescript is happy and the `defref` knows that  `'asset'` is a `SanityImageAsset` type.

```
.project((sub) => ({
  image: sub.field('image').project((subsub) => ({
    url: subsub.field('asset').deref().field('url'),
  })),

```
but it seems not intended. Is there some mistake on my side or is that a bug of the `defref` method?

-----

In your docs you often wrote for example

```
q.star.filterByType("product").project(sub => ({
  imageUrl: sub.field("image").deref().field("url", q.string()),
```

but that results in `{"imageUrl": image->.url}` groq query string and that does not work, because the `_ref` is in the `asset` field

**Comment by scottrippey** [comment]
It does seem like this is a bug in `deref`. I will investigate!
Also, you are correct that our doc samples are wrong for images, I'll get that fixed too!

**Comment by scottrippey** [comment]
The main issue I found was that `deref` worked for `null | Reference | Array<Reference>` but it didn't work for `Array<null | Reference>`.  So I fixed that in #335.  

The only thing I'm not totally sure about is whether this correctly covers your use-case.  It looks like `sub.field("image.asset").deref()` is only dealing with a single image, which ought to have the type `null | Reference` and that should be working correctly.  So we will have to see if this fix will solve your issue, or if your issue will remain.

Are you able to get a screenshot from your IDE when you hover over the `deref()` method?  That will tell me much more info, including the input type and the error message.

**Comment by scottrippey** [comment]
This has been published as 1.0.6, please test and report back if this fixed the issue!  Thanks!

**Comment by matzexcom** [comment]
Thanks for your quick reply and fixes.
Sadly, it does not fix it for me, but it seems the `deref` on hover changed from `unknown` to  `never` 

<img width="2851" alt="Image" src="https://github.com/user-attachments/assets/70e1dfe8-da70-406a-aab6-500e6718e278" />

**Comment by matzexcom** [comment]
If the deep dereferencing takes too much time, we can simply stick with the already working solution using the "double" field approach.
```TS
image: sub.field('image').field('asset').deref().field('url')
```
I wasn't aware that was possible when I created the issue.

**Comment by scottrippey** [comment]
I'd like to continue investigating this, but I need your help some more.  
It's hard to debug these "chaining" issues, because often, the problem lies earlier in the chain.  In this case, the `deref` is getting an "input" of `unknown` ... which comes from the `.field("image.asset")` chain.

Can you figure out why `.field("image.asset")` is giving an `unknown`, whereas the `.field("image").field("asset")` gives the correct type?  That part might be the heart of the issue.  If possible, can you post the Sanity type defs for that image?

I do have unit tests now that have `.field("image.asset")` but I'm not sure it's exactly the same as your scenario.

**Comment by matzexcom** [comment]
It seems like a straight forward type, nothing complex. For example our author entity/document is
```TS
// generated from sanity typegen
export type Author = {
  _id: string
  _type: 'author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  ...
}
```
I recorded some typing in my IDE,  may be that helps. Otherwise I don't know why .field().field() is working

https://github.com/user-attachments/assets/46faec1d-b1a4-4e72-a570-f30a56083a76


----

... After digging into the DeepDeref type, I might find the root of this problem.
DeepDeref handles arrays, null values, and reference types. However, it does not handle undefined values.
In my Author Schema, the image is optional. When I change the image so that it is not undefined, the deep deref works.

I wrote a failing test here
https://github.com/FormidableLabs/groqd/compare/main...matzexcom:fix/deep-deref

**Comment by scottrippey** [comment]
Thanks for digging in and finding that!  I'll start working on a fix!

**Comment by scottrippey** [comment]
The fix is published for deeply nested optional values!
This ought to fully fix this problem now! No more need to chain multiple `.field().field()` statements.
Please verify if this resolves your issue. Thanks!

**Comment by matzexcom** [comment]
🎉 it works like a charm
you indeed are a TS 🧙 
Thank you very much

**Comment by scottrippey** [comment]
This library has rewired my brain.  I have dreams in TS now.  It's weird :)

**Comment by alivault** [comment]
I am still getting this issue. On groqd `1.3.0`. `Argument of type '"url"' is not assignable to parameter of type 'never'.`

<img width="1068" alt="Image" src="https://github.com/user-attachments/assets/fc68e870-d797-44da-bc6f-8b48e12ea2c2" />

**Comment by m3hari** [comment]
Here is my related issue that cause our production crash with null pointer exception 😄  It might not be exact issue but this thread is the closest I found, hope the context helps debugging.

I have this query 
```ts
const postFragment = q.fragmentForType<'post'>().project((sub) => ({
  id: sub.field('_id'),
  language: sub.field('language'),
  slug: sub.field('slug').field('current'),
  title: sub.field('title'),
  _translations: q.star
    .filterByType('translation.metadata')
    .filterRaw('references(^._id)')
    .field('translations[].value')
    .deref()
    .project((sub) => ({
      id: sub.field('_id'),
      slug: sub.field('slug').field('current')
    }))
}))
```

Im using the `@sanity/document-internationalization` package for translation. I found  `translation.metadata` document is created for draft documents, pointing to a null.

`groqd` is inferring the result as:
```ts
_translations: GroqBuilder<{
  slug: string[];
  id: string[];
}[], Schema>
```

But it should have been including `null`, as 
```ts
_translations: GroqBuilder<({
  slug: string[];
  id: string[];
} | null)[], Schema>
```


Here is a related sanity codegen generated type.  `InternationalizedArrayReferenceValue.value` is nullable 
hence groqd should have inferred it too

```ts
export type InternationalizedArrayReferenceValue = {
  _type: 'internationalizedArrayReferenceValue'
  value?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'post'
  }
}


export type TranslationMetadata = {
  _id: string
  _type: 'translation.metadata'
  _createdAt: string
  _updatedAt: string
  _rev: string
  translations?: Array<
    {
      _key: string
    } & InternationalizedArrayReferenceValue
  >
  schemaTypes?: Array<string>
}
```

**Comment by scottrippey** [comment]
@alivault @m3hari If you're on the latest version of `groqd` (`1.6.0`), and you're still having trouble, please post a new issue. Thanks!

**Comment by m3hari** [comment]
Thank you, It did not fix it.  Will file new issue
